# Generated by Django 2.2 on 2022-01-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_project_app', '0002_auto_20220125_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='on_sale',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
